#pragma once

#include "EpiGraphics/gfxEnum.h"

#include <vulkan/vulkan.h>

EPI_NAMESPACE_BEGIN()

gfxFormat gfxFormatFrom(VkFormat formatVk);
gfxSurfaceColorSpace gfxSurfaceColorSpaceFrom(VkColorSpaceKHR colorSpaceVk);
gfxSurfaceTransformMask gfxSurfaceTransformMaskFrom(VkSurfaceTransformFlagsKHR mask);
gfxCompositeAlphaMask gfxCompositeAlphaMaskFrom(VkCompositeAlphaFlagsKHR mask);
gfxImageUsageMask gfxImageUsageMaskFrom(VkImageUsageFlags mask);
gfxFormatFeatureMask gfxFormatFeatureMaskFrom(VkFormatFeatureFlags mask);

VkFormat gfxFormatTo(gfxFormat format);
VkColorSpaceKHR gfxSurfaceColorSpaceTo(gfxSurfaceColorSpace colorSpace);
VkSurfaceTransformFlagBitsKHR gfxSurfaceTransformMaskTo(gfxSurfaceTransformMask mask);
VkCompositeAlphaFlagBitsKHR gfxCompositeAlphaMaskTo(gfxCompositeAlphaMask mask);
VkPresentModeKHR gfxSurfacePresentModeTo(gfxSurfacePresentMode presentMode);
VkPrimitiveTopology gfxPipelineInputAssemblyTypeTo(gfxPipelineInputAssemblyType type);
VkSampleCountFlagBits gfxSampleCountMaskTo(gfxSampleCountMask mask);
VkAttachmentLoadOp gfxAttachmentLoadOpTo(gfxAttachmentLoadOp loadOp);
VkAttachmentStoreOp gfxAttachmentStoreOpTo(gfxAttachmentStoreOp storeOp);
VkImageLayout gfxImageLayoutTo(gfxImageLayout layout);
VkPipelineBindPoint gfxPipelineBindPointTo(gfxPipelineBindPoint bindPoint);
VkPolygonMode gfxPolygonModeTo(gfxPolygonMode polygonMode);
VkCullModeFlagBits gfxCullModeTo(gfxCullMode cullMode);
VkFrontFace gfxFrontFaceTo(gfxFrontFace frontFace);
VkColorComponentFlagBits gfxColorComponentTo(gfxColorComponent colorComponent);
VkBlendFactor gfxBlendFactorTo(gfxBlendFactor blendFactor);
VkBlendOp gfxBlendOpTo(gfxBlendOp blendOp);
VkLogicOp gfxLogicOpTo(gfxLogicOp logicOp);
VkImageType gfxImageTypeTo(gfxImageType type);
VkImageViewType gfxImageViewTypeTo(gfxImageViewType viewType);
VkImageUsageFlagBits gfxImageUsageMaskTo(gfxImageUsageMask mask);
VkPipelineStageFlagBits gfxPipelineStageTo(gfxPipelineStage stage);
VkAccessFlagBits gfxAccessTo(gfxAccess access);
VkDependencyFlagBits gfxDependencyTo(gfxDependency dependency);
VkDynamicState gfxPipelineDynamicStateTo(gfxPipelineDynamicState state);
VkVertexInputRate gfxPipelineVertexInputRateTo(gfxPipelineVertexInputRate rate);
VkBufferUsageFlagBits gfxBufferUsageMaskTo(gfxBufferUsageMask mask);
VkMemoryPropertyFlagBits gfxDeviceMemoryPropertyMaskTo(gfxDeviceMemoryPropertyMask mask);
VkCommandBufferUsageFlagBits gfxCommandBufferUsageTo(gfxCommandBufferUsage usage);
VkCommandPoolCreateFlagBits gfxCommandPoolUsageTo(gfxCommandPoolUsage usage);
VkIndexType gfxIndexBufferTypeTo(gfxIndexBufferType type);
VkDescriptorSetLayoutCreateFlagBits gfxDescriptorSetLayoutUsageTo(gfxDescriptorSetLayoutUsage usage);
VkDescriptorType gfxDescriptorTypeTo(gfxDescriptorType type);
VkShaderStageFlagBits gfxShaderStageTo(gfxShaderStage mask);
VkDescriptorPoolCreateFlags gfxDescriptorPoolUsageTo(gfxDescriptorPoolUsage usage);
VkFenceCreateFlagBits gfxFenceCreateMaskTo(gfxFenceCreateMask mask);
VkSemaphoreCreateFlags gfxSemaphoreCreateMaskTo(gfxSemaphoreCreateMask mask);
VkSemaphoreWaitFlagBits gfxSemaphoreWaitMaskTo(gfxSemaphoreWaitMask mask);
VkImageTiling gfxImageTilingTo(gfxImageTiling tiling);
VkImageAspectFlagBits gfxImageAspectTo(gfxImageAspect mask);
VkCompareOp gfxCompareOpTo(gfxCompareOp op);
VkSamplerCreateFlagBits gfxSamplerCreateMaskTo(gfxSamplerCreateMask mask);
VkFilter gfxSamplerFilterModeTo(gfxSamplerFilterMode mode);
VkSamplerMipmapMode gfxSamplerMipmapModeTo(gfxSamplerMipmapMode mode);
VkSamplerAddressMode gfxSamplerAddressModeTo(gfxSamplerAddressMode mode);
VkBorderColor gfxSamplerBorderColorTo(gfxSamplerBorderColor borderColor);
VkComponentSwizzle gfxComponentSwizzleTo(gfxComponentSwizzle swizzle);
VkSharingMode gfxSharingModeTo(gfxSharingMode mode);
VkBufferCreateFlagBits gfxBufferCreateMaskTo(gfxBufferCreateMask mask);
VkImageCreateFlagBits gfxImageCreateMaskTo(gfxImageCreateMask mask);

EPI_NAMESPACE_END()
