#pragma once

#include "EpiGraphicsDriverCommon/gfxEnum.h"

#include <vulkan/vulkan.h>

EPI_NAMESPACE_BEGIN()

gfxFormat gfxFormatFrom(VkFormat formatVk);
gfxSurfaceColorSpace gfxSurfaceColorSpaceFrom(VkColorSpaceKHR colorSpaceVk);
gfxSurfaceTransform gfxSurfaceTransformFrom(VkSurfaceTransformFlagsKHR transform);
gfxCompositeAlpha gfxCompositeAlphaFrom(VkCompositeAlphaFlagsKHR compositeAlpha);
gfxImageUsage gfxImageUsageFrom(VkImageUsageFlags usage);

VkFormat gfxFormatTo(gfxFormat format);
VkColorSpaceKHR gfxSurfaceColorSpaceTo(gfxSurfaceColorSpace colorSpace);
VkSurfaceTransformFlagBitsKHR gfxSurfaceTransformTo(gfxSurfaceTransform transform);
VkPresentModeKHR gfxSurfacePresentModeTo(gfxSurfacePresentMode presentMode);
VkPrimitiveTopology gfxPipelineInputAssemblyTypeTo(gfxPipelineInputAssemblyType type);
VkSampleCountFlagBits gfxSampleCountTo(gfxSampleCount sampleCount);
VkAttachmentLoadOp gfxAttachmentLoadOpTo(gfxAttachmentLoadOp loadOp);
VkAttachmentStoreOp gfxAttachmentStoreOpTo(gfxAttachmentStoreOp storeOp);
VkImageLayout gfxImageLayoutTo(gfxImageLayout layout);
VkPipelineBindPoint gfxPipelineBindPointTo(gfxPipelineBindPoint bindPoint);
VkPolygonMode gfxPolygonModeTo(gfxPolygonMode polygonMode);
VkCullModeFlagBits gfxCullModeTo(gfxCullMode cullMode);
VkFrontFace gfxFrontFaceTo(gfxFrontFace frontFace);
VkColorComponentFlagBits gfxColorComponentTo(gfxColorComponent colorComponent);
VkBlendFactor gfxBlendFactorTo(gfxBlendFactor blendFactor);
VkBlendOp gfxBlendOpTo(gfxBlendOp blendOp);
VkLogicOp gfxLogicOpTo(gfxLogicOp logicOp);
VkImageType gfxTextureTypeTo(gfxTextureType type);
VkImageViewType gfxTextureViewTypeTo(gfxTextureViewType viewType);
VkImageUsageFlagBits gfxImageUsageTo(gfxImageUsage usage);
VkPipelineStageFlagBits gfxPipelineStageTo(gfxPipelineStage stage);
VkAccessFlagBits gfxAccessTo(gfxAccess access);
VkDependencyFlagBits gfxDependencyTo(gfxDependency dependency);
VkDynamicState gfxPipelineDynamicStateTo(gfxPipelineDynamicState state);
VkVertexInputRate gfxPipelineVertexInputRateTo(gfxPipelineVertexInputRate rate);
VkBufferUsageFlagBits gfxBufferUsageTo(gfxBufferUsage usage);
VkMemoryPropertyFlagBits gfxDeviceMemoryPropertyTo(gfxDeviceMemoryProperty properties);
VkCommandBufferUsageFlagBits gfxCommandBufferUsageTo(gfxCommandBufferUsage usage);
VkCommandPoolCreateFlagBits gfxCommandPoolUsageTo(gfxCommandPoolUsage usage);
VkIndexType gfxIndexBufferTypeTo(gfxIndexBufferType type);
VkDescriptorSetLayoutCreateFlagBits gfxDescriptorSetLayoutUsageTo(gfxDescriptorSetLayoutUsage usage);
VkDescriptorType gfxDescriptorTypeTo(gfxDescriptorType type);
VkShaderStageFlagBits gfxShaderStageTo(gfxShaderStage mask);
VkDescriptorPoolCreateFlags gfxDescriptorPoolUsageTo(gfxDescriptorPoolUsage usage);
VkFenceCreateFlagBits gfxFenceCreateMaskTo(gfxFenceCreateMask mask);
VkSemaphoreCreateFlags gfxSemaphoreCreateMaskTo(gfxSemaphoreCreateMask mask);
VkSemaphoreWaitFlagBits gfxSemaphoreWaitMaskTo(gfxSemaphoreWaitMask mask);
VkImageTiling gfxImageTilingTo(gfxImageTiling tiling);
VkImageAspectFlagBits gfxImageAspectTo(gfxImageAspect mask);

EPI_NAMESPACE_END()
